### ISSUE TITLE
Can we support customer-defined meta-data filter?

### ISSUE THREAD

**Issue by hongyuanlei** [buildkite/buildkite-agent-metrics#43]
Here's our meta-data defination:

```
meta-data="queue=${BuildKiteAgentQueue},docker=true,ci=true,market=${Market},env=${Env},region=${AWS::Region},version=${Version}"
```

As you can see, we put all the agents of the different env and the different region into the same queue but with different meta-data, In our pipeline, we can filter agent like this:

```
    agents:
      queue: ${BuildKiteAgentQueue}
      env: development
      market: ${market}
      region: ap-southeast-1
```

When I collect the buildkite agent metrics data, I also want to do the filter by env, region and other customer-defined metadata. Seems this tool can't support other meta-data filters.
